### ISSUE TITLE
Gateway on testnet is so slow

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/tfgateway#21]
### Environment 
[testnet](https://explorer.testnet.grid.tf/)

### Problem
After creating a [solution](https://zeroci.grid.tf/) using `threebot dashboard`, then expose this solution using the gateway on `testnet`, I found that it takes too much time to load the page, although it just takes couple of seconds to load from wireguard network.

**Comment by AhmedHanafy725** [comment]
The solution was expired, so I deployed another one, and it works fine now.

**Comment by xmonader** [comment]
this needs investigation (trc container) should be near to the deployed solution? or something else can be done @zaibon
