### ISSUE TITLE
All gateway deployed are missing the --domains flag

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/tfgateway#22]
For a gateway to support creation of subdomain it needs to know which domain he manages:
```
   --domains value          list of domain managed by this TFGateway. User can create free subdomain of any domain managed by TFGateway
```
Since all domain deploye in prod right now are supposed to allow subdomain creation, they needs to update updated to have this flag.

**Comment by delandtj** [comment]
sufficient like it is now I suppose ?
Close ?
