### ISSUE TITLE
After deleting gateway reservation, dns record is not properly removed

### ISSUE THREAD

**Issue by DylanVerstraete** [threefoldtech/tfgateway#23]
So I created a reservation to expose a solution

This is the reservation that I used for it:
https://explorer.grid.tf/explorer/reservations/9903

After canceling this reservation and recreating it did not propagate traffic to my container.
This is the reservation that I used for it:
https://explorer.grid.tf/explorer/reservations/9908

So in the end I ended up with exposing it to a different domain.

**Comment by muhamadazmy** [comment]
Fixed by #56
