### ISSUE TITLE
solution is not reached for hours 

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/tfgateway#27]
The solution is not reached for hours then it comes back.

![image](https://user-images.githubusercontent.com/41957921/92505506-7b42fc80-f204-11ea-8699-3909ca4721f1.png)

And when I checked the server it is running in this pod from 56 days, also the gateway itself is reached.

![image](https://user-images.githubusercontent.com/41957921/92505524-826a0a80-f204-11ea-8c29-913f12d21a9f.png)

**Reservations IDs:** 
kubernetes: https://explorer.testnet.grid.tf/explorer/reservations/461814
expose solution: https://explorer.testnet.grid.tf/explorer/reservations/461850

**Comment by zaibon** [comment]
Do you have any logs from the tcp router client by any chance ? I would like to make sure the problem doesn't come from there. Since it seems the gateway is reachable fine. I'm suspecting the connection failure maybe comes from the tcp router client instead.

**Comment by zaibon** [comment]
I've checked the logs from the gateway: https://gist.github.com/zaibon/e4c209c8cf5c9714ec90de1c4f0a498f
It seems indeed that most of the request coming in for zeroci.grid.tf are not proxies cause there is nowhere to forward them. Which seems to go in the direction that the tcp router client is indeed not properly connected to the server.
