### ISSUE TITLE
Gateway tests

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgateway#3]
Integration tests for tf_gateway that ensures the flow works resolving dns using coredns and correctly forwarding tcp traffic.

**Comment by AhmedHanafy725** [comment]
https://github.com/xmonader/tcprouter/issues/3

**Comment by AhmedHanafy725** [comment]
Local tests is added [here](https://github.com/threefoldtech/tf_gateway/tree/master/tests/local).
Remote tests are not fully done yet, waiting for storing records remotely to be finished.

**Comment by AhmedHanafy725** [comment]
https://github.com/threefoldtech/tf_gateway/issues/7 as a temporary solution, records is stored before starting coredns server.
