### ISSUE TITLE
 Misconfigured gateway DNS nameserver  

### ISSUE THREAD

**Issue by waleedhammam** [threefoldtech/tfgateway#32]
- In this gateway: https://explorer.grid.tf/api/v1/gateways/FVjKQYTXoUmdyhs9nKh3yqVRnsvG4bSyh6wYLHReWKeW
the name server is 
```
  "dns_nameserver": [
    "tf-gateway-prod-05"
  ],
```
which is not resolvable.

```
 File "/home/waleed/js-sdk/jumpscale/sals/marketplace/apps_chatflow.py", line 284, in infrastructure_setup
    self._get_domain()
    │    └ <function MarketPlaceAppsChatflow._get_domain at 0x7f9be5d5a9d0>
    └ <marketplace.chats.mattermost.MattermostDeploy object at 0x7f9be57515e0>

  File "/home/waleed/js-sdk/jumpscale/sals/marketplace/apps_chatflow.py", line 253, in _get_domain
    self.addresses.append(j.sals.nettools.get_host_by_name(ns))
    │    │         │      │ │                              └ 'tf-gateway-prod-05'
    │    │         │      │ └ <property object at 0x7f9bf2670400>
    │    │         │      └ <jumpscale.loader.J object at 0x7f9bf2657970>
    │    │         └ <method 'append' of 'list' objects>
    │    └ []
    └ <marketplace.chats.mattermost.MattermostDeploy object at 0x7f9be57515e0>

  File "/home/waleed/.cache/pypoetry/virtualenvs/js-sdk-6NoanB64-py3.8/lib/python3.8/site-packages/jumpscale/sals/nettools/__init__.py", line 375, in get_host_by_name
    return socket.gethostbyname(dnsHostname)
           │      │             └ 'tf-gateway-prod-05'
           │      └ <function gethostbyname at 0x7f9bf2b248b0>
           └ <module 'socket' from '/usr/lib/python3.8/socket.py'>
  File "/home/waleed/.cache/pypoetry/virtualenvs/js-sdk-6NoanB64-py3.8/lib/python3.8/site-packages/gevent/_socketcommon.py", line 163, in gethostbyname
    return get_hub().resolver.gethostbyname(hostname)
           │                                └ 'tf-gateway-prod-05'

➜  js-sdk git:(development) nslookup tf-gateway-prod-05
Server:    127.0.0.53
Address:  127.0.0.53#53

** server can't find tf-gateway-prod-05: SERVFAIL
```

**Comment by delandtj** [comment]
errr ... you need an FQDN to resolve non-local hostnames.
second, 127.0.0.1#53 -> means that you run al local resolver in js-sdk ?

**Comment by xmonader** [comment]
![image](https://user-images.githubusercontent.com/64129/94443417-7212d300-01a5-11eb-95a2-4d2c8cc9efb9.png)
the data coming from explorer the dns_nameserver `tf-gateway-prod-05`

and on the other one dns_nameserver `tf-gateway-testnet-01.gateway.tf`
![image](https://user-images.githubusercontent.com/64129/94443579-9e2e5400-01a5-11eb-9616-00cb9ba54c06.png)

**Comment by zaibon** [comment]
@delandtj seems the faulty gateway is started with a wrong value for the `nameservers` flag. Can you double check and correct it if it's needed please

**Comment by delandtj** [comment]
- a `-` in a name while it shoudn't in 3x0.tf -> also prologued the domain that was going to expire 04/10/2020
- in base.tf, the NS records were CNAME records... 
in hindsight... should've seen it, but ... yeah... hard to spot at first sight

Omar, Ahmed, can you ultimately verify and close this issue ?

**Comment by zaibon** [comment]
@delandtj can you edit the home README and add it the expected config of all DNS records required for a gateway to work properly please.

**Comment by OmarElawady** [comment]
@delandtj 

I tried deploying subdomains on all managed domains and all worked except for these two:

63c9341f-3.tfgw-prod-05.3x0.me

d4492452-1.tfgw-prod-05.base.tf

The websites they're pointing to is probably long gone (curling won't work) but the subdomain workloads are still their so:
- `dig d4492452-1.tfgw-prod-05.base.tf` doesn't work, but `dig d4492452-1.tfgw-prod-05.base.tf @tf-gateway-prod-05.gateway.tf` does. And the same for  the 3x0.me one.

**Comment by zaibon** [comment]
gateway FVjKQYTXoUmdyhs9nKh3yqVRnsvG4bSyh6wYLHReWKeW was not properly configured and was claiming to manage the wrong domain. It has been properly configued now, things should be better.

![Uploading 2020-10-01_3153x559_scrot.png…]()

**Comment by OmarElawady** [comment]
I tested all the managed domains by deploying a subdomain and a proxy for this managed domain and checking:
1. The domain is resolvable.
2. I can access it globally.
3. I can access it if I send and http request directed to the gateway ip with the header "Host: subdomain"

All of them passed the third check. The failed ones didn't pass the first two.

Not working:
tfgw-prod-05.3x0.me
tfgw-prod-05.base.tf
tfgw-prod-01.3x0.me
tfgw-prod-01.ava.tf
tfgw-prod-01.base.tf
tfgw-prod-02.3x0.me
tfgw-prod-02.ava.tf
tfgw-prod-02.base.tf
tfgw-prod-03.3x0.me
tfgw-prod-03.ava.tf
tfgw-prod-03.base.tf
tfgw-prod-04.3x0.me
tfgw-prod-04.ava.tf
tfgw-prod-04.base.tf
tfgw-prod-06.3x0.me
tfgw-prod-06.ava.tf
tfgw-prod-06.base.tf
tfgw-prod-07.3x0.me
tfgw-prod-07.ava.tf

Working:
tfgw-prod-05.gateway.tf
tfgw-prod-05.ava.tf
tfgw-prod-01.gateway.tf
tfgw-prod-02.gateway.tf
tfgw-prod-03.gateway.tf
tfgw-prod-04.gateway.tf
tfgw-prod-06.gateway.tf
tfgw-prod-07.gateway.tf
tfgw-prod-07.base.tf

**Comment by OmarElawady** [comment]
After @delandtj's update here https://github.com/threefoldtech/tfgateway/issues/36#issuecomment-703537686 . All managed domains are working fine except for tfgw-prod-06.ava.tf

**Comment by delandtj** [comment]
so I can close this one too
