### ISSUE TITLE
Gateway incorrectly reports a managed domain

### ISSUE THREAD

**Issue by OmarElawady** [threefoldtech/tfgateway#34]
The gateway `FVjKQYTXoUmdyhs9nKh3yqVRnsvG4bSyh6wYLHReWKeW` reports that it manages gateway.tf, but deploying a subdomain on it gives this error:
![Screenshot from 2020-09-29 12-42-07](https://user-images.githubusercontent.com/13040543/94548565-37667480-0251-11eb-82ae-eaae02d3864c.png)

**Comment by zaibon** [comment]
![2020-10-01_3153x559_scrot](https://user-images.githubusercontent.com/303164/94816390-0bd3bd80-03fc-11eb-887d-124d4c8187ce.png)
@delandtj did fix this gateway
