### ISSUE TITLE
secret cannot be empty

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgateway#48]
http://explorer.testnet.grid.tf/api/v1/reservations/workloads/512436
http://explorer.testnet.grid.tf/api/v1/reservations/workloads/512477

while the trc secret is clearly passed in the reservation as shown in the screenshot
![image](https://user-images.githubusercontent.com/64129/100675954-97bc8400-3370-11eb-8c4f-70d3bf30a167.png)

**Comment by xmonader** [comment]
caused because of https://github.com/threefoldtech/tfgateway/issues/35

**Comment by muhamadazmy** [comment]
Can u please send me the version of this gateway by running `tfgateway -v` ?

**Comment by muhamadazmy** [comment]
Already fixed
