### ISSUE TITLE
Reverse proxies are failing on devnet

### ISSUE THREAD

**Issue by m-motawea** [threefoldtech/tfgateway#49]
reverse proxy workloads are failing with error `secret cannot be empty` but the secret is not empty as seen in the workload.
https://explorer.devnet.grid.tf/api/v1/reservations/workloads/5105
https://explorer.devnet.grid.tf/api/v1/reservations/workloads/5098

**Comment by muhamadazmy** [comment]
The gatway has been downgraded by accident on devnet. we restored the latest version, could you please try again
