### ISSUE TITLE
Failed to deploy in time on testnet for subdomain on csfarmer

### ISSUE THREAD

**Issue by waleedhammam** [threefoldtech/tfgateway#58]
CS farmer gateway on testnet doesn't accept reservations

workload: https://explorer.testnet.grid.tf/api/v1/reservations/workloads/1074

**Comment by waleedhammam** [comment]
Logs from gateway

![image](https://user-images.githubusercontent.com/10658229/104847925-3f731e80-58eb-11eb-80ee-2dcac170321e.png)

**Comment by muhamadazmy** [comment]
the logs says that this is a ZDB workload type. Can I have the gateway ID please ?

**Comment by muhamadazmy** [comment]
It seems that the wrong type of reservation was created on this gateway. The gateway should still skip this reservation and continue, instead of getting stuck.
