### ISSUE TITLE
SDK Manual - review and revise gateway documentation

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldtech/tfgateway#66]
## webgateway review

Owner: Weynand
- in wiki and in repo
- documentation so everyone can set one up (anyone!!)
- review if there are any issues to do with redundancy of configuration, ...
- how to register in explorer

**Comment by weynandkuijpers** [comment]
Documentation restyled and rewritten.

https://github.com/threefoldtech/tfgateway/tree/master
